-- ============================================================================
-- GMA SCHOOL MANAGEMENT SYSTEM - INITIAL DATA
-- Run this after schema.sql to populate the database with initial data
-- ============================================================================

-- Default roles
INSERT INTO roles (name) VALUES
('ADMIN'),
('INSTRUCTOR'),
('DIRECTOR'),
('STUDENT');

-- Default member types
INSERT INTO member_types (name) VALUES
('Regular'),
('Prospect'),
('Women\'s self defense'),
('Instructor'),
('Workshop'),
('Parent');

-- Default levels (belt ranks)
INSERT INTO levels (code, display_name, order_seq, description) VALUES
('BASIC', 'Basic', 1, 'Basic level for beginners'),
('WHITE', 'White', 2, 'White belt level'),
('BLUE', 'Blue', 3, 'Blue belt level'),
('GREEN', 'Green', 4, 'Green belt level'),
('BROWN', 'Brown', 5, 'Brown belt level'),
('BLACK', 'Black', 6, 'Black belt level'),
('TEEN', 'Teen', 7, 'Teen level program');

-- Move Categories
INSERT INTO move_categories (name, description) VALUES
('General', 'Default category for moves'),
('Stances & Footwork', 'Basic stances, footwork, and movement patterns'),
('Strikes', 'Hand strikes, punches, palm strikes, elbow strikes'),
('Kicks', 'All kicking techniques and variations'),
('Blocks & Deflections', 'Defensive hand techniques and blocks'),
('Grappling & Escapes', 'Grappling, chokes, escapes, and ground techniques'),
('Weapons', 'Weapon techniques and disarms'),
('Training Drills', 'Focus mitt drills, pad work, and training exercises'),
('Forms & Patterns', 'Traditional forms, Chi Sao, and pattern work'),
('Testing', 'Tests, evaluations, and equipment requirements');

-- ============================================================================
-- MOVES (unique techniques organized by category)
-- ============================================================================

INSERT INTO moves (name, description, move_categories_id) VALUES
-- Stances & Footwork (category_id = 2)
('Basic Stance', NULL, 2),
('Safe Training Distance', NULL, 2),
('Closing Stance', NULL, 2),
('Ready Stance', NULL, 2),
('Ready to Closing with Straight Punches', NULL, 2),
('Basic Shuffle', NULL, 2),
('Lunge Close from Shuffle', NULL, 2),
('Side Step 1', NULL, 2),
('Side Step 2', NULL, 2),
('Side Step 3', NULL, 2),
('Side Step 4', NULL, 2),
('Cut Corner Half Step', NULL, 2),
('Change Direction Half Step', NULL, 2),
('Reverse Shuffle', NULL, 2),
('Run Through Close', NULL, 2),
('Hidden Step', NULL, 2),
('Step Through', NULL, 2),
('Step Over', NULL, 2),
('Snap Close', NULL, 2),
('Switch Step', NULL, 2),
('Half Step Closing', NULL, 2),
('Closing from Motion', NULL, 2),
('Slant Back Ready Stance', NULL, 2),

-- Strikes (category_id = 3)
('Correct Fist', NULL, 3),
('Straight Punching', NULL, 3),
('Continuous Punch Close', NULL, 3),
('Single Punch Close', NULL, 3),
('Palm Strikes', NULL, 3),
('Elbow Strikes', NULL, 3),
('High Hook', NULL, 3),
('Low Hook', NULL, 3),
('Uppercut', NULL, 3),
('Qua Choi', NULL, 3),
('Forearm Strike', NULL, 3),
('Knee Strikes', NULL, 3),
('Eye Gouge', NULL, 3),
('Throat Strikes', NULL, 3),
('Forearm Smash', NULL, 3),
('Lunge Punch', NULL, 3),
('Power Striking', NULL, 3),
('Converging', NULL, 3),
('Close Range Combo', NULL, 3),

-- Kicks (category_id = 4)
('Front Thrust Kick - Lead', NULL, 4),
('Front Thrust Kick - Rear', NULL, 4),
('Sole Kick - Lead', NULL, 4),
('Sole Kick - Rear', NULL, 4),
('Side Thrust', NULL, 4),
('Roundhouse', NULL, 4),
('Rear Snap', NULL, 4),
('Side Snap', NULL, 4),
('Toe Kick', NULL, 4),
('Sole Kick', NULL, 4),
('Rear Thrust Kick - Rear', NULL, 4),
('Rear Thrust Kick Lead', NULL, 4),
('Turning Rear Thrust Kick', NULL, 4),
('Lead Leg Kicking Combo', NULL, 4),
('Rear Leg Kicking Combo', NULL, 4),
('Mixed Kicking Combo', NULL, 4),
('Cut Kick', NULL, 4),
('Rear Thrust Kick - Chambered', NULL, 4),
('Front Thrust Kick - Chambered', NULL, 4),
('Side Thrust Kick - Chambered', NULL, 4),

-- Blocks & Deflections (category_id = 5)
('Pak Sao', NULL, 5),
('Taun Sao', NULL, 5),
('Bong Sao', NULL, 5),
('Jum Sao', NULL, 5),
('Gum Sao', NULL, 5),
('Gaun Sao', NULL, 5),
('Inner / Outer Deflecting', NULL, 5),
('Inner Deflecting', NULL, 5),
('Outer Deflecting', NULL, 5),
('Double Gaun Sao', NULL, 5),
('Kwan Sao', NULL, 5),
('Forearm Kick Block', NULL, 5),
('Shin Block', NULL, 5),
('Soft Pak Sao', NULL, 5),
('Knee Block', NULL, 5),
('Double Fook Sao', NULL, 5),
('Double Bong Sao', NULL, 5),

-- Grappling & Escapes (category_id = 6)
('Wrist Grab Escapes', NULL, 6),
('Basic Choke Escape - Rear / Front / Side', NULL, 6),
('Technical Standup', NULL, 6),
('Wrist Grab and Arm Grab Escapes', NULL, 6),
('Bear Hug Escape #1', NULL, 6),
('Bear Hug Escape #2', NULL, 6),
('Bear Hug Escape #3', NULL, 6),
('Bear Hug Escape #4', NULL, 6),
('Wall Escape Front', NULL, 6),
('Wall Escape Back', NULL, 6),
('Front Grab Prevention', NULL, 6),
('Rear Naked Choke', NULL, 6),
('Chicken Wing / Power Hammer Lock', NULL, 6),
('Straight Arm Bar', NULL, 6),
('Hart Trap', NULL, 6),
('2-on-1 Sticking', NULL, 6),
('Drop Close', NULL, 6),
('Slap Trap / Qua Choi', NULL, 6),
('High Hand Trap', NULL, 6),
('High Hand Double Trap Straight In', NULL, 6),
('Wrist Grab into Arm Bar', NULL, 6),
('Wrist Grab into Sweep', NULL, 6),
('Elbow Rollover Counters', NULL, 6),
('Hair Grab Back', NULL, 6),
('Hair Grab Front', NULL, 6),
('Rear Naked Choke Variation', NULL, 6),
('Wrist Grab Flow R-R', NULL, 6),
('Wrist Grab Flow R-L', NULL, 6),
('Jacket Choke', NULL, 6),
('Jacket Choke Counter', NULL, 6),
('Cross Jacket Choke', NULL, 6),
('Cross Jacket Choke Counter', NULL, 6),
('Standing Guillotine', NULL, 6),
('Standing Guillotine Counter', NULL, 6),
('Straight Arm Bars - Standard, Short, Body Trap', NULL, 6),
('Reverse Arm Bar', NULL, 6),
('Grappling - Deep Integration and Flow', NULL, 6),

-- Weapons (category_id = 7)
('Stick: Starting Position / Proper Striking / Distance', NULL, 7),
('Box Pattern', NULL, 7),
('Heaven Pattern', NULL, 7),
('Basic Pattern', NULL, 7),
('Earth Pattern', NULL, 7),
('Pistol Disarm Front', NULL, 7),
('Cincotero', NULL, 7),
('Side / Rear / Back Pistol Disarm', NULL, 7),
('Rifle / Shotgun Disarm', NULL, 7),
('Knife Defense / Use', NULL, 7),
('Level 1 & 2 Sticks with Checking Hands', NULL, 7),

-- Training Drills (category_id = 8)
('Focus Mitt Drill #1', NULL, 8),
('Focus Mitt Drill #2', NULL, 8),
('Focus Mitt Drill #3', NULL, 8),
('Focus Mitt Drill #4', NULL, 8),
('Thai Pad Drill #1', NULL, 8),
('Thai Pad Drill #2', NULL, 8),
('Thai Pad Drill #3', NULL, 8),
('Thai Pad Drill #4', NULL, 8),
('Foot Position and Body Control', NULL, 8),
('Attacking a Kicker', NULL, 8),
('Head Movement', NULL, 8),
('Paired Attacks', NULL, 8),
('Distance Awareness', NULL, 8),
('Speed Changing', NULL, 8),
('Speed Training', NULL, 8),
('Speed Drill', NULL, 8),
('AT - Bill Jee 1', NULL, 8),
('AT - Bill Jee 2', NULL, 8),
('AT - Jum Sao', NULL, 8),
('AT - Taun Sao', NULL, 8),
('AT - Bong Sao', NULL, 8),
('AT - Drop Close', NULL, 8),
('AT - Forearm', NULL, 8),
('AT - Outer Deflecting', NULL, 8),
('AT - Pak Sao', NULL, 8),
('AT - Straight Punching', NULL, 8),
('DT - Kwun Sao', NULL, 8),
('DT - Mon Sao', NULL, 8),

-- Forms & Patterns (category_id = 9)
('Mook Jong (MJ) Low Bong Sao', NULL, 9),
('MJ - Double Gaun Sao (Basic Training)', NULL, 9),
('MJ - Kwan Sao (Basic Training)', NULL, 9),
('MJ - Alternating DG Sao / KS (Basic Training)', NULL, 9),
('MJ - Inner / Outer Deflecting', NULL, 9),
('MJ - Pak Sao', NULL, 9),
('MJ - Bong Sao', NULL, 9),
('MJ - Gum Sao', NULL, 9),
('MJ - Gaun Sao', NULL, 9),
('MJ - Double Gaun Sao', NULL, 9),
('MJ - Kwan Sao', NULL, 9),
('Sole Kick - Lead on Mook Jong', NULL, 9),
('Sole Kick - Rear on Mook Jong', NULL, 9),
('Trapping Strikes Pattern', NULL, 9),
('Palm Sticking', NULL, 9),
('Chi Sao Basic Understanding', NULL, 9),
('Pak Sao - MJ', NULL, 9),
('Pak Sao - Partner Practice', NULL, 9),
('Bong Sao - MJ', NULL, 9),
('Bong Sao - Partner Practice', NULL, 9),
('Gum Sao - MJ', NULL, 9),
('Gum Sao - Partner Practice', NULL, 9),
('Gaun Sao #1 - MJ', NULL, 9),
('Gaun Sao #1 - Partner Practice', NULL, 9),
('Gaun Sao #2 - MJ', NULL, 9),
('Gaun Sao #2 - Partner Practice', NULL, 9),
('Gaun Sao #3 - MJ', NULL, 9),
('Gaun Sao #3 - Partner Practice', NULL, 9),
('Double Gaun Sao #1 - MJ', NULL, 9),
('Double Gaun Sao #1 - Partner Practice', NULL, 9),
('Double Gaun Sao #2 - MJ', NULL, 9),
('Double Gaun Sao #2 - Partner Practice', NULL, 9),
('Kwun Sao - MJ', NULL, 9),
('Kwun Sao Partner Practice', NULL, 9),
('Chi Sao Positions', NULL, 9),
('Chi Sao Patterns', NULL, 9),
('Chi Sao Load', NULL, 9),
('Chi Sao Angle', NULL, 9),
('Mook Jong Series 3', NULL, 9),
('Engagement Taun Sao 1', NULL, 9),
('Engagement Taun Sao 2', NULL, 9),
('Engagement Taun Sao 3', NULL, 9),
('Engagement Taun Sao 4', NULL, 9),
('Engagement Taun Sao 5', NULL, 9),
('Engagement Taun Sao 6', NULL, 9),
('Engagement Taun Sao 7', NULL, 9),
('Engagement Taun Sao 8', NULL, 9),
('Engagement Bong Sao 1', NULL, 9),
('Engagement Bong Sao 2', NULL, 9),
('Engagement Bong Sao 3', NULL, 9),
('Engagement Bong Sao 4', NULL, 9),
('Engagement Soft Pak Sao 1', NULL, 9),
('Engagement Soft Pak Sao 2', NULL, 9),
('Engagement Soft Pak Sao 3', NULL, 9),
('Engagement Pak Dar 1', NULL, 9),
('Engagement Pak Dar 2', NULL, 9),
('Engagement Pak Dar 3', NULL, 9),
('Engagement Pak Dar 4', NULL, 9),
('Engagement Pak Dar 5', NULL, 9),
('Engagement Pak Dar 6', NULL, 9),
('Engagement Pak Sao 1', NULL, 9),
('Engagement Gaun Sao', NULL, 9),
('Engagement Straight Punching', NULL, 9),

-- Testing (category_id = 10)
('Boundary Setting Physical & Verbal', NULL, 10),
('Written Test', NULL, 10),
('Equipment', NULL, 10),
('Kick Jamming Test', NULL, 10),
('Sparring Test', NULL, 10),
('Free Sparring Knife Disarm Test', NULL, 10),
('Free Sparring Stick Use', NULL, 10),
('Leg Strength Test - Stairs or Weights', NULL, 10),
('Kick Jamming Test - Min of 35 / 40', NULL, 10),
('Sparring Test - 3 Rounds', NULL, 10),
('Sparring Test - 6 Rounds - 3 AT / 3 DT', NULL, 10);

-- ============================================================================
-- LEVEL REQUIREMENTS (linking moves to levels with sort order)
-- ============================================================================

-- Basic - Level 1 (level_id = 1)
INSERT INTO level_requirements (level_id, move_id, sort_order, level_specific_notes, is_required) VALUES
(1, (SELECT id FROM moves WHERE name = 'Basic Stance'), 1, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Safe Training Distance'), 2, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Closing Stance'), 3, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Ready Stance'), 4, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Ready to Closing with Straight Punches'), 5, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Correct Fist'), 6, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Straight Punching'), 7, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Palm Strikes'), 8, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Elbow Strikes'), 9, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Wrist Grab Escapes'), 10, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Boundary Setting Physical & Verbal'), 11, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Written Test'), 12, NULL, 1),
(1, (SELECT id FROM moves WHERE name = 'Equipment'), 13, NULL, 1),

-- White - Level 2 (level_id = 2)
(2, (SELECT id FROM moves WHERE name = 'Continuous Punch Close'), 1, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Single Punch Close'), 2, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Palm Strikes'), 3, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Knee Strikes'), 4, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Eye Gouge'), 5, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Throat Strikes'), 6, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Elbow Strikes'), 7, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'High Hook'), 8, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Low Hook'), 9, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Uppercut'), 10, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Front Thrust Kick - Lead'), 11, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Front Thrust Kick - Rear'), 12, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Sole Kick - Lead'), 13, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Sole Kick - Rear'), 14, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Pak Sao'), 15, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Taun Sao'), 16, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Bong Sao'), 17, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Jum Sao'), 18, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Gum Sao'), 19, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Gaun Sao'), 20, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Inner / Outer Deflecting'), 21, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Basic Choke Escape - Rear / Front / Side'), 22, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Technical Standup'), 23, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Wrist Grab and Arm Grab Escapes'), 24, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Bear Hug Escape #1'), 25, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Bear Hug Escape #2'), 26, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Wall Escape Front'), 27, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Wall Escape Back'), 28, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Written Test'), 29, NULL, 1),
(2, (SELECT id FROM moves WHERE name = 'Equipment'), 30, NULL, 1),

-- Blue - Level 3 (level_id = 3)
(3, (SELECT id FROM moves WHERE name = 'Qua Choi'), 1, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Forearm Strike'), 2, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Palm Strikes'), 3, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Elbow Strikes'), 4, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'High Hook'), 5, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Low Hook'), 6, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Uppercut'), 7, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Focus Mitt Drill #1'), 8, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Focus Mitt Drill #2'), 9, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Focus Mitt Drill #3'), 10, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Focus Mitt Drill #4'), 11, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Front Thrust Kick - Lead'), 12, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Front Thrust Kick - Rear'), 13, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Side Thrust'), 14, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Roundhouse'), 15, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Rear Snap'), 16, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Side Snap'), 17, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Toe Kick'), 18, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Sole Kick'), 19, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Thai Pad Drill #1'), 20, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Thai Pad Drill #2'), 21, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Thai Pad Drill #3'), 22, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Thai Pad Drill #4'), 23, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Basic Shuffle'), 24, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Lunge Close from Shuffle'), 25, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Side Step 1'), 26, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Side Step 2'), 27, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Side Step 3'), 28, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Side Step 4'), 29, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Pak Sao'), 30, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Taun Sao'), 31, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Bong Sao'), 32, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Jum Sao'), 33, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Gum Sao'), 34, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Gaun Sao'), 35, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Inner Deflecting'), 36, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Outer Deflecting'), 37, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Double Gaun Sao'), 38, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Kwan Sao'), 39, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Forearm Kick Block'), 40, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Shin Block'), 41, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Hart Trap'), 42, NULL, 1),
(3, (SELECT id FROM moves WHERE name = '2-on-1 Sticking'), 43, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Front Grab Prevention'), 44, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Rear Naked Choke'), 45, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Chicken Wing / Power Hammer Lock'), 46, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Straight Arm Bar'), 47, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Bear Hug Escape #2'), 48, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Bear Hug Escape #3'), 49, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Bear Hug Escape #4'), 50, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Mook Jong (MJ) Low Bong Sao'), 51, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'MJ - Double Gaun Sao (Basic Training)'), 52, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'MJ - Kwan Sao (Basic Training)'), 53, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'MJ - Alternating DG Sao / KS (Basic Training)'), 54, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'MJ - Inner / Outer Deflecting'), 55, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'MJ - Pak Sao'), 56, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'MJ - Bong Sao'), 57, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'MJ - Gum Sao'), 58, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'MJ - Gaun Sao'), 59, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'MJ - Double Gaun Sao'), 60, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'MJ - Kwan Sao'), 61, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Sole Kick - Lead on Mook Jong'), 62, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Sole Kick - Rear on Mook Jong'), 63, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Stick: Starting Position / Proper Striking / Distance'), 64, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Box Pattern'), 65, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Heaven Pattern'), 66, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Basic Pattern'), 67, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Earth Pattern'), 68, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Pistol Disarm Front'), 69, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Kick Jamming Test'), 70, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Sparring Test'), 71, NULL, 1),
(3, (SELECT id FROM moves WHERE name = 'Written Test'), 72, NULL, 1),

-- Green - Level 4 (level_id = 4)
(4, (SELECT id FROM moves WHERE name = 'Knee Strikes'), 1, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Forearm Strike'), 2, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Elbow Strikes'), 3, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Converging'), 4, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Rear Thrust Kick - Rear'), 5, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Rear Thrust Kick Lead'), 6, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Turning Rear Thrust Kick'), 7, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Lead Leg Kicking Combo'), 8, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Rear Leg Kicking Combo'), 9, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Mixed Kicking Combo'), 10, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Foot Position and Body Control'), 11, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Cut Corner Half Step'), 12, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Change Direction Half Step'), 13, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Reverse Shuffle'), 14, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Run Through Close'), 15, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Side Step 1'), 16, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Side Step 2'), 17, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Side Step 3'), 18, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Side Step 4'), 19, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Bong Sao'), 20, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Double Gaun Sao'), 21, 'Double Gaun Sao / Kwan Sao', 1),
(4, (SELECT id FROM moves WHERE name = 'Kwan Sao'), 22, 'Double Gaun Sao / Kwan Sao', 1),
(4, (SELECT id FROM moves WHERE name = 'Soft Pak Sao'), 23, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Knee Block'), 24, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Shin Block'), 25, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Trapping Strikes Pattern'), 26, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Palm Sticking'), 27, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Hart Trap'), 28, NULL, 1),
(4, (SELECT id FROM moves WHERE name = '2-on-1 Sticking'), 29, '2 on 1 Sticking', 1),
(4, (SELECT id FROM moves WHERE name = 'Drop Close'), 30, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Slap Trap / Qua Choi'), 31, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'High Hand Trap'), 32, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'High Hand Double Trap Straight In'), 33, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Wrist Grab into Arm Bar'), 34, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Wrist Grab into Sweep'), 35, 'Wrist Grap into Sweep', 1),
(4, (SELECT id FROM moves WHERE name = 'Elbow Rollover Counters'), 36, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Double Fook Sao'), 37, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Double Bong Sao'), 38, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Chi Sao Basic Understanding'), 39, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Chicken Wing / Power Hammer Lock'), 40, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Straight Arm Bars - Standard, Short, Body Trap'), 41, 'Straight Arm Bars - standard, short, body trap', 1),
(4, (SELECT id FROM moves WHERE name = 'Reverse Arm Bar'), 42, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Hair Grab Back'), 43, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Hair Grab Front'), 44, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Rear Naked Choke'), 45, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Rear Naked Choke Variation'), 46, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Wrist Grab Flow R-R'), 47, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Wrist Grab Flow R-L'), 48, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Jacket Choke'), 49, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Jacket Choke Counter'), 50, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Cross Jacket Choke'), 51, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Cross Jacket Choke Counter'), 52, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Standing Guillotine'), 53, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Standing Guillotine Counter'), 54, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Pak Sao - MJ'), 55, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Pak Sao - Partner Practice'), 56, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Bong Sao - MJ'), 57, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Bong Sao - Partner Practice'), 58, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Gum Sao - MJ'), 59, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Gum Sao - Partner Practice'), 60, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Gaun Sao #1 - MJ'), 61, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Gaun Sao #1 - Partner Practice'), 62, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Gaun Sao #2 - MJ'), 63, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Gaun Sao #2 - Partner Practice'), 64, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Gaun Sao #3 - MJ'), 65, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Gaun Sao #3 - Partner Practice'), 66, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Double Gaun Sao #1 - MJ'), 67, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Double Gaun Sao #1 - Partner Practice'), 68, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Double Gaun Sao #2 - MJ'), 69, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Double Gaun Sao #2 - Partner Practice'), 70, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Kwun Sao - MJ'), 71, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Kwun Sao Partner Practice'), 72, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Cincotero'), 73, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Side / Rear / Back Pistol Disarm'), 74, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Rifle / Shotgun Disarm'), 75, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Knife Defense / Use'), 76, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Free Sparring Knife Disarm Test'), 77, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Free Sparring Stick Use'), 78, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Leg Strength Test - Stairs or Weights'), 79, NULL, 1),
(4, (SELECT id FROM moves WHERE name = 'Kick Jamming Test - Min of 35 / 40'), 80, 'Kick Jamming Test- Min of 35 / 40', 1),
(4, (SELECT id FROM moves WHERE name = 'Sparring Test - 3 Rounds'), 81, 'Sparring Test - 3 Rounds', 1),
(4, (SELECT id FROM moves WHERE name = 'Written Test'), 82, NULL, 1),

-- Brown - Level 5 (level_id = 5)
(5, (SELECT id FROM moves WHERE name = 'Power Striking'), 1, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Lunge Punch'), 2, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Palm Strikes'), 3, 'Palm Strike', 1),
(5, (SELECT id FROM moves WHERE name = 'Knee Strikes'), 4, 'Knee Strike', 1),
(5, (SELECT id FROM moves WHERE name = 'Forearm Smash'), 5, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Elbow Strikes'), 6, 'Elbow Strikes - down / across', 1),
(5, (SELECT id FROM moves WHERE name = 'Converging'), 7, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Close Range Combo'), 8, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Sole Kick'), 9, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Cut Kick'), 10, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Rear Thrust Kick - Chambered'), 11, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Front Thrust Kick - Chambered'), 12, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Side Thrust Kick - Chambered'), 13, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Hidden Step'), 14, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Step Through'), 15, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Step Over'), 16, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Snap Close'), 17, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Switch Step'), 18, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Half Step Closing'), 19, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Closing from Motion'), 20, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Attacking a Kicker'), 21, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Head Movement'), 22, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Paired Attacks'), 23, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Distance Awareness'), 24, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Slant Back Ready Stance'), 25, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Speed Changing'), 26, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Speed Training'), 27, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Speed Drill'), 28, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'AT - Bill Jee 1'), 29, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'AT - Bill Jee 2'), 30, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'AT - Jum Sao'), 31, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'AT - Taun Sao'), 32, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'AT - Bong Sao'), 33, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'AT - Drop Close'), 34, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'AT - Forearm'), 35, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'AT - Outer Deflecting'), 36, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'AT - Pak Sao'), 37, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'AT - Straight Punching'), 38, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'DT - Kwun Sao'), 39, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'DT - Mon Sao'), 40, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Chi Sao Positions'), 41, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Chi Sao Patterns'), 42, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Chi Sao Load'), 43, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Chi Sao Angle'), 44, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Grappling - Deep Integration and Flow'), 45, 'Grappling - deep integration and flow', 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Taun Sao 1'), 46, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Taun Sao 2'), 47, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Taun Sao 3'), 48, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Taun Sao 4'), 49, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Taun Sao 5'), 50, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Taun Sao 6'), 51, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Taun Sao 7'), 52, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Taun Sao 8'), 53, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Bong Sao 1'), 54, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Bong Sao 2'), 55, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Bong Sao 3'), 56, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Bong Sao 4'), 57, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Soft Pak Sao 1'), 58, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Soft Pak Sao 2'), 59, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Soft Pak Sao 3'), 60, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Pak Dar 1'), 61, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Pak Dar 2'), 62, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Pak Dar 3'), 63, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Pak Dar 4'), 64, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Pak Dar 5'), 65, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Pak Dar 6'), 66, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Pak Sao 1'), 67, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Gaun Sao'), 68, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Engagement Straight Punching'), 69, 'Engagement Straight punching', 1),
(5, (SELECT id FROM moves WHERE name = 'Mook Jong Series 3'), 70, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Level 1 & 2 Sticks with Checking Hands'), 71, 'Level 1 & 2 sticks with checking hands', 1),
(5, (SELECT id FROM moves WHERE name = 'Side / Rear / Back Pistol Disarm'), 72, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Rifle / Shotgun Disarm'), 73, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Knife Defense / Use'), 74, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Free Sparring Knife Disarm Test'), 75, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Free Sparring Stick Use'), 76, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Leg Strength Test - Stairs or Weights'), 77, NULL, 1),
(5, (SELECT id FROM moves WHERE name = 'Sparring Test - 6 Rounds - 3 AT / 3 DT'), 78, 'Sparring test - 6 rounds - 3 AT / 3 DT', 1),
(5, (SELECT id FROM moves WHERE name = 'Written Test'), 79, NULL, 1);

-- ============================================================================
-- STUDENT DATA (from current enrollment)
-- ============================================================================

-- Active Users and Students Data (48 total: 40 adults + 8 teens)
-- © 2025-2026 Hector Torres - Greenlake Martial Arts

-- Users (email as username) - 48 users
INSERT INTO users (username, password_hash) VALUES
('aiden@grimmhistory.com', '$2a$10$defaulthash'),
('ben.r.alvord@gmail.com', '$2a$10$defaulthash'),
('breckm@hotmail.com', '$2a$10$defaulthash'),
('brianbiladeau@gmail.com', '$2a$10$defaulthash'),
('bridorf@gmail.com', '$2a$10$defaulthash'),
('leukothea@gmail.com', '$2a$10$defaulthash'),
('ctcarsley@hotmail.com', '$2a$10$defaulthash'),
('daniel.willyard@hotmail.com', '$2a$10$defaulthash'),
('david_mxfld@yahoo.com', '$2a$10$defaulthash'),
('deb@zaret.com', '$2a$10$defaulthash'),
('emweisser@gmail.com', '$2a$10$defaulthash'),
('emmajnielsen6@comcast.net', '$2a$10$defaulthash'),
('erandall26@gmail.com', '$2a$10$defaulthash'),
('yuane45632@yahoo.com', '$2a$10$defaulthash'),
('erinlbrowning@gmail.com', '$2a$10$defaulthash'),
('fabien.lescot@gmail.com', '$2a$10$defaulthash'),
('gsabben@gmail.com', '$2a$10$defaulthash'),
('gnila@live.com', '$2a$10$defaulthash'),
('torrhes@gmail.com', '$2a$10$defaulthash'),
('jacob.greenleaf@gmail.com', '$2a$10$defaulthash'),
('jimparfitt53@gmail.com', '$2a$10$defaulthash'),
('jasonrgarfield@gmail.com', '$2a$10$defaulthash'),
('jay@knot-eye.com', '$2a$10$defaulthash'),
('jef7psp@gmail.com', '$2a$10$defaulthash'),
('jessmcole@hotmail.com', '$2a$10$defaulthash'),
('johncarney1073@gmail.com', '$2a$10$defaulthash'),
('j.gardiner@hotmail.com', '$2a$10$defaulthash'),
('jhughes2011@gmail.com', '$2a$10$defaulthash'),
('j@jdiaz.io', '$2a$10$defaulthash'),
('mskarenlawson@gmail.com', '$2a$10$defaulthash'),
('Gwywnnydd@gmail.com', '$2a$10$defaulthash'),
('lafcadiod@yahoo.com', '$2a$10$defaulthash'),
('Lemliah@protonmail.com', '$2a$10$defaulthash'),
('lee.mackenzieh@gmail.com', '$2a$10$defaulthash'),
('marie_guirriec@hotmail.com', '$2a$10$defaulthash'),
('Matt@greenlakemartialarts.com', '$2a$10$defaulthash'),
('maylynn.wilkins@gmail.com', '$2a$10$defaulthash'),
('beardesign13@gmail.com', '$2a$10$defaulthash'),
('mona.wilding@gmail.com', '$2a$10$defaulthash'),
('nickleanok@yahoo.com', '$2a$10$defaulthash'),
('kristofer_everett@yahoo.com', '$2a$10$defaulthash'),
('raqber13@gmail.com', '$2a$10$defaulthash'),
('sberk10@gmail.com', '$2a$10$defaulthash'),
('sprather013@gmail.com', '$2a$10$defaulthash'),
('stacee9118@gmail.com', '$2a$10$defaulthash'),
('teresarchen@gmail.com', '$2a$10$defaulthash'),
('y.ten.brug@gmail.com', '$2a$10$defaulthash'),
('madelinecaron1@gmail.com', '$2a$10$defaulthash')

-- Students - 48 students
INSERT INTO students (user_id, first_name, last_name, email, phone, address, member_type_id, signup_date, is_active) VALUES
((SELECT id FROM users WHERE username = 'aiden@grimmhistory.com'), 'Aiden', 'Prather', 'aiden@grimmhistory.com', '206-909-1927', '13739 22nd Ave NE. Seattle, WA 98125', (SELECT id FROM member_types WHERE name = 'Regular'), NULL, true),
((SELECT id FROM users WHERE username = 'ben.r.alvord@gmail.com'), 'Ben', 'Alvord', 'ben.r.alvord@gmail.com', '425-248-8288', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2025-10-23', true),
((SELECT id FROM users WHERE username = 'breckm@hotmail.com'), 'Breck', 'McKean', 'breckm@hotmail.com', '425-870-8796', '3711 164th St SW 228', (SELECT id FROM member_types WHERE name = 'Regular'), '2009-11-14', true),
((SELECT id FROM users WHERE username = 'brianbiladeau@gmail.com'), 'Brian', 'Biladeau', 'brianbiladeau@gmail.com', '208-850-1031', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2012-12-08', true),
((SELECT id FROM users WHERE username = 'bridorf@gmail.com'), 'Brian', 'Wendorf', 'bridorf@gmail.com', '206-817-8825', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2024-06-18', true),
((SELECT id FROM users WHERE username = 'leukothea@gmail.com'), 'Catherine', 'Warren', 'leukothea@gmail.com', '206-579-0547', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2024-03-09', true),
((SELECT id FROM users WHERE username = 'ctcarsley@hotmail.com'), 'Chris', 'Carsley', 'ctcarsley@hotmail.com', '206-755-8835', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2013-05-09', true),
((SELECT id FROM users WHERE username = 'daniel.willyard@hotmail.com'), 'Dan', 'Willyard', 'daniel.willyard@hotmail.com', '971-280-4001', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), NULL, true),
((SELECT id FROM users WHERE username = 'david_mxfld@yahoo.com'), 'David', 'Maxfield', 'david_mxfld@yahoo.com', '206-854-5188', 'P.O. Box 4112', (SELECT id FROM member_types WHERE name = 'Parent'), '2007-05-24', true),
((SELECT id FROM users WHERE username = 'deb@zaret.com'), 'Deb', 'Zaret', 'deb@zaret.com', NULL, NULL, (SELECT id FROM member_types WHERE name = 'Parent'), '2024-03-28', true),
((SELECT id FROM users WHERE username = 'emweisser@gmail.com'), 'Emily', 'Weisser', 'emweisser@gmail.com', NULL, NULL, (SELECT id FROM member_types WHERE name = 'Regular'), NULL, true),
((SELECT id FROM users WHERE username = 'emmajnielsen6@comcast.net'), 'Emma', 'Nielsen', 'emmajnielsen6@comcast.net', '503-991-9036', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2022-11-01', true),
((SELECT id FROM users WHERE username = 'erandall26@gmail.com'), 'Emma', 'Randall', 'erandall26@gmail.com', '206-617-5749', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), NULL, true),
((SELECT id FROM users WHERE username = 'yuane45632@yahoo.com'), 'Eric', 'Yuan', 'yuane45632@yahoo.com', NULL, NULL, (SELECT id FROM member_types WHERE name = 'Parent'), '2025-07-20', true),
((SELECT id FROM users WHERE username = 'erinlbrowning@gmail.com'), 'Erin', 'Browning', 'erinlbrowning@gmail.com', '971-533-7721', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2023-02-08', true),
((SELECT id FROM users WHERE username = 'fabien.lescot@gmail.com'), 'Fabien', 'Lescot', 'fabien.lescot@gmail.com', NULL, NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2025-09-29', true),
((SELECT id FROM users WHERE username = 'gsabben@gmail.com'), 'Gaelle', 'Sabben', 'gsabben@gmail.com', '404-683-3103', NULL, (SELECT id FROM member_types WHERE name = 'Instructor'), '2017-11-17', true),
((SELECT id FROM users WHERE username = 'gnila@live.com'), 'Geneva', 'Neubauer', 'gnila@live.com', '208-699-6738', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2015-04-04', true),
((SELECT id FROM users WHERE username = 'torrhes@gmail.com'), 'Hector', 'Torres', 'torrhes@gmail.com', '206-397-2286', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2025-08-21', true),
((SELECT id FROM users WHERE username = 'jacob.greenleaf@gmail.com'), 'Jacob', 'Greenleaf', 'jacob.greenleaf@gmail.com', '206-669-5194', NULL, (SELECT id FROM member_types WHERE name = 'Instructor'), '2017-03-23', true),
((SELECT id FROM users WHERE username = 'jimparfitt53@gmail.com'), 'James', 'Parfitt', 'jimparfitt53@gmail.com', NULL, NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2024-09-21', true),
((SELECT id FROM users WHERE username = 'jasonrgarfield@gmail.com'), 'Jason', 'Garfield', 'jasonrgarfield@gmail.com', NULL, NULL, (SELECT id FROM member_types WHERE name = 'Parent'), '2024-03-08', true),
((SELECT id FROM users WHERE username = 'jay@knot-eye.com'), 'Jay', 'Sachdev', 'jay@knot-eye.com', '415-999-0052', NULL, (SELECT id FROM member_types WHERE name = 'Instructor'), NULL, true),
((SELECT id FROM users WHERE username = 'jef7psp@gmail.com'), 'Jef', 'Faulkner', 'jef7psp@gmail.com', '206-713-2715', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2010-10-21', true),
((SELECT id FROM users WHERE username = 'jessmcole@hotmail.com'), 'Jessica', 'Cole', 'jessmcole@hotmail.com', '206-788-5880', NULL, (SELECT id FROM member_types WHERE name = 'Parent'), '2025-06-25', true),
((SELECT id FROM users WHERE username = 'johncarney1073@gmail.com'), 'John', 'Carney', 'johncarney1073@gmail.com', '208-721-7880', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2025-11-06', true),
((SELECT id FROM users WHERE username = 'j.gardiner@hotmail.com'), 'Josh', 'Gardiner', 'j.gardiner@hotmail.com', '206-370-2787', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2021-07-26', true),
((SELECT id FROM users WHERE username = 'jhughes2011@gmail.com'), 'Joshua', 'Hughes', 'jhughes2011@gmail.com', '253-709-7033', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), NULL, true),
((SELECT id FROM users WHERE username = 'j@jdiaz.io'), 'Julian', 'Diaz', 'j@jdiaz.io', '201-406-5688', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2025-03-15', true),
((SELECT id FROM users WHERE username = 'mskarenlawson@gmail.com'), 'Karen', 'Lawson', 'mskarenlawson@gmail.com', '646-238-2543', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2024-10-01', true),
((SELECT id FROM users WHERE username = 'Gwywnnydd@gmail.com'), 'Karyn', 'Vicker', 'Gwywnnydd@gmail.com', '206-406-1225', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2017-11-11', true),
((SELECT id FROM users WHERE username = 'lafcadiod@yahoo.com'), 'Lafcadio', 'Darling', 'lafcadiod@yahoo.com', '206-398-9234', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), NULL, true),
((SELECT id FROM users WHERE username = 'Lemliah@protonmail.com'), 'Laura', 'Howe', 'Lemliah@protonmail.com', '458-245-5708', NULL, (SELECT id FROM member_types WHERE name = 'Parent'), '2025-04-26', true),
((SELECT id FROM users WHERE username = 'lee.mackenzieh@gmail.com'), 'Mackenzie', 'Lee', 'lee.mackenzieh@gmail.com', '208-949-5420', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2024-03-09', true),
((SELECT id FROM users WHERE username = 'marie_guirriec@hotmail.com'), 'Marie', 'Guirriec', 'marie_guirriec@hotmail.com', NULL, NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2025-09-29', true),
((SELECT id FROM users WHERE username = 'Matt@greenlakemartialarts.com'), 'Matt', 'Soule', 'Matt@greenlakemartialarts.com', '206-313-9964', NULL, (SELECT id FROM member_types WHERE name = 'Instructor'), NULL, true),
((SELECT id FROM users WHERE username = 'maylynn.wilkins@gmail.com'), 'Maylynn', 'Wilkins', 'maylynn.wilkins@gmail.com', NULL, NULL, (SELECT id FROM member_types WHERE name = 'Parent'), NULL, true),
((SELECT id FROM users WHERE username = 'beardesign13@gmail.com'), 'Michael', 'Angelo', 'beardesign13@gmail.com', '425-287-4340', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2020-01-09', true),
((SELECT id FROM users WHERE username = 'mona.wilding@gmail.com'), 'Mona', 'Wilding', 'mona.wilding@gmail.com', '206-861-2216', '5116 Keystone Pl N', (SELECT id FROM member_types WHERE name = 'Regular'), '2008-02-05', true),
((SELECT id FROM users WHERE username = 'nickleanok@yahoo.com'), 'Nicholas', 'Pierce', 'nickleanok@yahoo.com', NULL, NULL, (SELECT id FROM member_types WHERE name = 'Parent'), '2024-04-03', true),
((SELECT id FROM users WHERE username = 'kristofer_everett@yahoo.com'), 'Ozzy (Kris)', 'Everett', 'kristofer_everett@yahoo.com', '206-698-7617', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2018-03-17', true),
((SELECT id FROM users WHERE username = 'raqber13@gmail.com'), 'Raquel', 'Bermudez', 'raqber13@gmail.com', '206-214-8139', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2025-03-15', true),
((SELECT id FROM users WHERE username = 'sberk10@gmail.com'), 'Samantha', 'Berk', 'sberk10@gmail.com', '571-309-6909', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), NULL, true),
((SELECT id FROM users WHERE username = 'sprather013@gmail.com'), 'Sean', 'Prather', 'sprather013@gmail.com', '206-276-3813', '13739 22nd Ave NE. Seattle, WA 98125', (SELECT id FROM member_types WHERE name = 'Regular'), '2008-04-28', true),
((SELECT id FROM users WHERE username = 'stacee9118@gmail.com'), 'Stacee', 'Dang', 'stacee9118@gmail.com', '360-824-0580', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2025-06-07', true),
((SELECT id FROM users WHERE username = 'teresarchen@gmail.com'), 'Teresa', 'Martirosov', 'teresarchen@gmail.com', '626-818-6607', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2025-11-06', true),
((SELECT id FROM users WHERE username = 'y.ten.brug@gmail.com'), 'Yme', 'ten-Brug', 'y.ten.brug@gmail.com', '206-608-1764', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2024-10-01', true),
((SELECT id FROM users WHERE username = 'madelinecaron1@gmail.com'), 'Madeline', 'Caron', 'madelinecaron1@gmail.com', '206-265-3273', NULL, (SELECT id FROM member_types WHERE name = 'Regular'), '2025-09-26', true)

-- Student Level Assignments
INSERT INTO student_levels (student_id, level_id) VALUES
-- BLUE Level (10 students)
((SELECT id FROM students WHERE email = 'aiden@grimmhistory.com'), (SELECT id FROM levels WHERE code = 'BLUE')),
((SELECT id FROM students WHERE email = 'breckm@hotmail.com'), (SELECT id FROM levels WHERE code = 'BLUE')),
((SELECT id FROM students WHERE email = 'bridorf@gmail.com'), (SELECT id FROM levels WHERE code = 'BLUE')),
((SELECT id FROM students WHERE email = 'leukothea@gmail.com'), (SELECT id FROM levels WHERE code = 'BLUE')),
((SELECT id FROM students WHERE email = 'emmajnielsen6@comcast.net'), (SELECT id FROM levels WHERE code = 'BLUE')),
((SELECT id FROM students WHERE email = 'jhughes2011@gmail.com'), (SELECT id FROM levels WHERE code = 'BLUE')),
((SELECT id FROM students WHERE email = 'mona.wilding@gmail.com'), (SELECT id FROM levels WHERE code = 'BLUE')),
((SELECT id FROM students WHERE email = 'kristofer_everett@yahoo.com'), (SELECT id FROM levels WHERE code = 'BLUE')),
((SELECT id FROM students WHERE email = 'sberk10@gmail.com'), (SELECT id FROM levels WHERE code = 'BLUE')),
((SELECT id FROM students WHERE email = 'y.ten.brug@gmail.com'), (SELECT id FROM levels WHERE code = 'BLUE')),

-- WHITE Level (10 students)
((SELECT id FROM students WHERE email = 'ben.r.alvord@gmail.com'), (SELECT id FROM levels WHERE code = 'WHITE')),
((SELECT id FROM students WHERE email = 'emweisser@gmail.com'), (SELECT id FROM levels WHERE code = 'WHITE')),
((SELECT id FROM students WHERE email = 'erinlbrowning@gmail.com'), (SELECT id FROM levels WHERE code = 'WHITE')),
((SELECT id FROM students WHERE email = 'torrhes@gmail.com'), (SELECT id FROM levels WHERE code = 'WHITE')),
((SELECT id FROM students WHERE email = 'jimparfitt53@gmail.com'), (SELECT id FROM levels WHERE code = 'WHITE')),
((SELECT id FROM students WHERE email = 'mskarenlawson@gmail.com'), (SELECT id FROM levels WHERE code = 'WHITE')),
((SELECT id FROM students WHERE email = 'Gwywnnydd@gmail.com'), (SELECT id FROM levels WHERE code = 'WHITE')),
((SELECT id FROM students WHERE email = 'lee.mackenzieh@gmail.com'), (SELECT id FROM levels WHERE code = 'WHITE')),
((SELECT id FROM students WHERE email = 'raqber13@gmail.com'), (SELECT id FROM levels WHERE code = 'WHITE')),
((SELECT id FROM students WHERE email = 'stacee9118@gmail.com'), (SELECT id FROM levels WHERE code = 'WHITE')),

-- GREEN Level (9 students)
((SELECT id FROM students WHERE email = 'brianbiladeau@gmail.com'), (SELECT id FROM levels WHERE code = 'GREEN')),
((SELECT id FROM students WHERE email = 'daniel.willyard@hotmail.com'), (SELECT id FROM levels WHERE code = 'GREEN')),
((SELECT id FROM students WHERE email = 'erandall26@gmail.com'), (SELECT id FROM levels WHERE code = 'GREEN')),
((SELECT id FROM students WHERE email = 'gsabben@gmail.com'), (SELECT id FROM levels WHERE code = 'GREEN')),
((SELECT id FROM students WHERE email = 'gnila@live.com'), (SELECT id FROM levels WHERE code = 'GREEN')),
((SELECT id FROM students WHERE email = 'jay@knot-eye.com'), (SELECT id FROM levels WHERE code = 'GREEN')),
((SELECT id FROM students WHERE email = 'jef7psp@gmail.com'), (SELECT id FROM levels WHERE code = 'GREEN')),
((SELECT id FROM students WHERE email = 'j.gardiner@hotmail.com'), (SELECT id FROM levels WHERE code = 'GREEN')),
((SELECT id FROM students WHERE email = 'beardesign13@gmail.com'), (SELECT id FROM levels WHERE code = 'GREEN')),

-- BROWN Level (2 students)
((SELECT id FROM students WHERE email = 'ctcarsley@hotmail.com'), (SELECT id FROM levels WHERE code = 'BROWN')),
((SELECT id FROM students WHERE email = 'jacob.greenleaf@gmail.com'), (SELECT id FROM levels WHERE code = 'BROWN')),

-- BASIC Level (8 students)
((SELECT id FROM students WHERE email = 'fabien.lescot@gmail.com'), (SELECT id FROM levels WHERE code = 'BASIC')),
((SELECT id FROM students WHERE email = 'johncarney1073@gmail.com'), (SELECT id FROM levels WHERE code = 'BASIC')),
((SELECT id FROM students WHERE email = 'j@jdiaz.io'), (SELECT id FROM levels WHERE code = 'BASIC')),
((SELECT id FROM students WHERE email = 'lafcadiod@yahoo.com'), (SELECT id FROM levels WHERE code = 'BASIC')),
((SELECT id FROM students WHERE email = 'marie_guirriec@hotmail.com'), (SELECT id FROM levels WHERE code = 'BASIC')),
((SELECT id FROM students WHERE email = 'sprather013@gmail.com'), (SELECT id FROM levels WHERE code = 'BASIC')),
((SELECT id FROM students WHERE email = 'teresarchen@gmail.com'), (SELECT id FROM levels WHERE code = 'BASIC')),
((SELECT id FROM students WHERE email = 'madelinecaron1@gmail.com'), (SELECT id FROM levels WHERE code = 'BASIC'))

-- BLACK Level (1 student - Instructor)
((SELECT id FROM students WHERE email = 'Matt@greenlakemartialarts.com'), (SELECT id FROM levels WHERE code = 'BLACK')),

-- TEEN Level (8 Parent accounts)
((SELECT id FROM students WHERE email = 'david_mxfld@yahoo.com'), (SELECT id FROM levels WHERE code = 'TEEN')),
((SELECT id FROM students WHERE email = 'deb@zaret.com'), (SELECT id FROM levels WHERE code = 'TEEN')),
((SELECT id FROM students WHERE email = 'yuane45632@yahoo.com'), (SELECT id FROM levels WHERE code = 'TEEN')),
((SELECT id FROM students WHERE email = 'jasonrgarfield@gmail.com'), (SELECT id FROM levels WHERE code = 'TEEN')),
((SELECT id FROM students WHERE email = 'jessmcole@hotmail.com'), (SELECT id FROM levels WHERE code = 'TEEN')),
((SELECT id FROM students WHERE email = 'Lemliah@protonmail.com'), (SELECT id FROM levels WHERE code = 'TEEN')),
((SELECT id FROM students WHERE email = 'maylynn.wilkins@gmail.com'), (SELECT id FROM levels WHERE code = 'TEEN')),
((SELECT id FROM students WHERE email = 'nickleanok@yahoo.com'), (SELECT id FROM levels WHERE code = 'TEEN'));
